CREATE TABLE KhachHang
(
MaKH NVARCHAR(10) PRIMARY KEY,
HoTenKH NVARCHAR(50),
DiaChi NVARCHAR(50),
SDT NVARCHAR(10)
)


CREATE TABLE Xe(
	SoXe NVARCHAR(10) PRIMARY KEY,
	HangXe NVARCHAR(20),
	NamSX INT ,
	MaKH NVARCHAR(10) FOREIGN KEY REFERENCES dbo.KhachHang(MaKH)
	)

CREATE TABLE BaoDuong
(
	MaBD NVARCHAR(10) PRIMARY KEY,
	NgayGioNhan NVARCHAR(10),
	NgayGioTra NVARCHAR(10),
	SoKM INT,
	NoiDung NVARCHAR(255),
	SoXe NVARCHAR(10) FOREIGN KEY REFERENCES dbo.Xe(SoXe)

)

CREATE TABLE CongViec
(
	MaCV NVARCHAR(10) PRIMARY KEY,
	TenCongViec NVARCHAR(50),
	DonGia INT 
)

CREATE TABLE CT_BD
(
	MaBD NVARCHAR(10) FOREIGN KEY REFERENCES dbo.BaoDuong(MaBD),
	MaCV NVARCHAR(10) FOREIGN KEY REFERENCES dbo.CongViec(MaCV)
	CONSTRAINT PK_KEY PRIMARY KEY(MaBD, MaCV)
	)




